alias: 3D-Drucker
description: ''
trigger:
- platform: device
  type: turned_on
  device_id: 56661d1855347f947a777e4fb31309a0
  entity_id: switch.tasmota_2
  domain: switch
condition: []
action:
- wait_for_trigger:
  - platform: numeric_state
    entity_id: sensor.tasmota_energy_power_2
    for:
      hours: 0
      minutes: 15
      seconds: 0
    below: 15
- if:
  - condition: device
    device_id: 399153156e7b834e4e1f6b6ddb5bd1dd
    domain: media_player
    entity_id: media_player.lg_b9
    type: is_on
  then:
  - service: notify.fernseher
    data:
      message: Druck um {{as_timestamp(now()) | timestamp_custom('%H:%M Uhr')}}
        abgeschlossen.
- service: notify.gotify
  data:
    title: 3D Drucker
    message: Druck um {{as_timestamp(now()) | timestamp_custom('%H:%M Uhr')}} abgeschlossen.
- type: turn_off
  device_id: 56661d1855347f947a777e4fb31309a0
  entity_id: switch.tasmota_2
  domain: switch
  enabled: true
mode: single

