alias: Auto-Update
description: ''
trigger:
- platform: state
  entity_id:
  - update.home_assistant_core_update
  - update.home_assistant_operating_system_update
  - update.home_assistant_supervisor_update
condition: []
action:
- wait_for_trigger:
  - platform: time
    at: 03:00:00
  continue_on_timeout: false
  enabled: true
- service: update.install
  data: {}
  target:
    entity_id: all
- service: notify.gotify
  data:
    message: '{{ trigger.entity_id }} Update wurde ausgeführt'
    title: Homeassistent
mode: parallel
max: 10

