alias: Flurlicht
description: ''
trigger:
- platform: state
  entity_id:
  - binary_sensor.flur_bewegung_erkannt
  to: 'on'
  from: 'off'
  id: 'ON'
- platform: state
  entity_id:
  - binary_sensor.flur_keine_bewegung_erkannt
  to: 'on'
  id: 'OFF'
  from: 'off'
condition:
- condition: state
  entity_id: binary_sensor.anwesend
  state: 'on'
action:
- choose:
  - conditions:
    - condition: trigger
      id: 'ON'
    sequence:
    - choose:
      - conditions:
        - condition: and
          conditions:
          - condition: state
            entity_id: sensor.sonnenaufgang
            state: Sonnenuntergang
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: input_number.flur_licht_abends
        sequence:
        - service: light.turn_on
          data: {}
          target:
            entity_id: light.flur
      - conditions:
        - condition: and
          conditions:
          - condition: state
            entity_id: sensor.sonnenaufgang
            state: Sonnenaufgang
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: input_number.flur_licht_fruh
        sequence:
        - service: light.turn_on
          data: {}
          target:
            entity_id: light.flur
  - conditions:
    - condition: device
      type: is_on
      device_id: c92919e4da0f3e84110f0e1bc2dfa3d2
      entity_id: switch.shellyplus1_441793a3e76c_switch_0
      domain: switch
    - condition: trigger
      id: 'OFF'
    sequence:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.flur
  default: []
mode: single

