id: '1673228103761'
alias: Klima
description: 'Abwesend: Bei einer Stunde Abwesenheit werden alle Heizungen in den
  Eco-Modus versetzt (16 Grad).
  Anwesenheit: Bei Anwesenheit wird der Eco-Modus wieder deaktiviert und die vor
  eingestellten Heizprofile wieder aktiviert.'
trigger:
- platform: state
  entity_id:
  - binary_sensor.anwesend
  to: 'off'
  for:
    hours: 3
    minutes: 0
    seconds: 0
  id: Abwesend
- platform: state
  entity_id:
  - binary_sensor.anwesend
  from: 'off'
  to: 'on'
  id: Anwesend
  for:
    hours: 3
    minutes: 0
    seconds: 0
condition: []
action:
- choose:
  - conditions:
    - condition: trigger
      id: Abwesend
    sequence:
    - service: homematicip_cloud.activate_eco_mode_with_duration
      data:
        duration: 1440
        accesspoint_id: 3014XXXXXXXXXXXXXXXXXXXX
  - conditions:
    - condition: trigger
      id: Anwesend
    sequence:
    - service: homematicip_cloud.deactivate_eco_mode
      data:
        accesspoint_id: 3014XXXXXXXXXXXXXXXXXXXX
    - service: climate.set_temperature
      data:
        temperature: '{{ states(''input_number.wohungs_temperatur'') }}'
      target:
        area_id:
        - buro
        - wohnzimmer
mode: single
