alias: Küche
description: ''
trigger:
- platform: device
  device_id: e63d7afbcf7e0943762c75cef2332a73
  domain: shelly
  type: single_push
  subtype: button1
  id: On/Off
- platform: device
  device_id: e63d7afbcf7e0943762c75cef2332a73
  domain: shelly
  type: long_push
  subtype: button1
  id: Musik
- platform: device
  device_id: 399153156e7b834e4e1f6b6ddb5bd1dd
  domain: media_player
  entity_id: media_player.lg_b9
  type: turned_on
  id: TV einschalten
condition: []
action:
- choose:
  - conditions:
    - condition: trigger
      id: On/Off
    sequence:
    - choose:
      - conditions:
        - condition: state
          entity_id: light.kuche_licht
          state: 'off'
        - condition: or
          conditions:
          - condition: state
            entity_id: sensor.szenenauswahl
            state: scene.wohnzimmer_hell
          - condition: state
            entity_id: sensor.szenenauswahl
            state: scene.wohnzimmer_fairfax
        sequence:
        - service: switch.turn_on
          data: {}
          target:
            device_id: 57f5ff61c232c7b17260ce91834d2320
        - service: scene.turn_on
          target:
            entity_id: '{{ states(''sensor.szenenauswahl'') }}'
          metadata: {}
      - conditions:
        - condition: state
          entity_id: light.kuche_licht
          state: 'off'
        - condition: not
          conditions:
          - condition: state
            entity_id: sensor.szenenauswahl
            state: scene.wohnzimmer_hell
          - condition: state
            entity_id: sensor.szenenauswahl
            state: scene.wohnzimmer_fairfax
        sequence:
        - service: switch.turn_on
          data: {}
          target:
            device_id: 57f5ff61c232c7b17260ce91834d2320
      - conditions:
        - condition: state
          entity_id: light.kuche_licht
          state: 'on'
        sequence:
        - service: light.turn_off
          data:
            transition: 2
          target:
            area_id:
            - kuche
            - wohnzimmer
  - conditions:
    - condition: trigger
      id: Musik
    sequence:
    - choose:
      - conditions:
        - condition: not
          conditions:
          - condition: state
            entity_id: media_player.wohnzimmer
            state: playing
        sequence:
        - service: input_select.select_next
          data:
            cycle: true
          target:
            entity_id: input_select.playlisten
        - service: media_player.volume_set
          data:
            volume_level: 0.36
          target:
            entity_id:
            - media_player.wohnzimmer
            - media_player.allen_lautsprechern
        - service: media_player.play_media
          target:
            entity_id: media_player.wohnzimmer
          data:
            media_content_id: spotify://67abeeecded744aec5181c0e9c3af164/spotify:playlist:{{
              states('input_select.playlisten') }}
            media_content_type: spotify://playlist
          enabled: true
        - parallel:
          - service: media_player.shuffle_set
            data:
              shuffle: true
            target:
              entity_id: media_player.spotify_erik
          - service: media_player.media_next_track
            data: {}
            target:
              entity_id: media_player.wohnzimmer
          - choose:
            - conditions:
              - condition: device
                device_id: 399153156e7b834e4e1f6b6ddb5bd1dd
                domain: media_player
                entity_id: media_player.lg_b9
                type: is_on
              - condition: state
                entity_id: media_player.lg_b9
                attribute: is_volume_muted
                state: false
              sequence:
              - service: media_player.volume_mute
                data:
                  is_volume_muted: true
                target:
                  device_id: 399153156e7b834e4e1f6b6ddb5bd1dd
              - service: webostv.command
                data:
                  entity_id: media_player.lg_b9
                  command: com.webos.service.tvpower/power/turnOffScreen
      - conditions:
        - condition: state
          entity_id: media_player.wohnzimmer
          state: playing
        sequence:
        - service: media_player.turn_off
          data: {}
          target:
            entity_id: media_player.wohnzimmer
        - if:
          - condition: device
            device_id: 399153156e7b834e4e1f6b6ddb5bd1dd
            domain: media_player
            entity_id: media_player.lg_b9
            type: is_on
          - condition: state
            entity_id: media_player.lg_b9
            attribute: is_volume_muted
            state: true
          then:
          - service: media_player.volume_mute
            data:
              is_volume_muted: false
            target:
              device_id: 399153156e7b834e4e1f6b6ddb5bd1dd
          - service: webostv.command
            data:
              entity_id: media_player.lg_b9
              command: com.webos.service.tvpower/power/turnOnScreen
  - conditions:
    - condition: trigger
      id: TV einschalten
    - condition: state
      entity_id: media_player.wohnzimmer
      state: playing
    sequence:
    - service: media_player.turn_off
      data: {}
      target:
        entity_id: media_player.wohnzimmer
mode: single

