id: '1672974392118'
alias: Küche Staubsaugen
description: 'Doppelter Tastendruck: Die Zone ''Küchenzeile'' wird durch den Staubsauger
  Gereinigt.'
trigger:
- platform: device
  device_id: e63d7afbcf7e0943762c75cef2332a73
  domain: shelly
  type: double_push
  subtype: button1
condition: []
action:
- service: xiaomi_miio.vacuum_clean_zone
  data:
    zone:
    - - 20117
      - 22994
      - 21417
      - 26594
  target:
    entity_id: vacuum.roborock_vacuum_a10
mode: single
