id: '1671474285814'
alias: Monatliches Backup
description: Am 01. jeden Monats wird ein Voll-Backup erstellt und vorhandene alte
  Backups werden gelöscht. Benachrichtigung erfolgt via Push-Benachrichtigung.
trigger:
- platform: time
  at: 00:01:00
condition:
- condition: template
  value_template: '{{ now().day == 1 }}'
action:
- service: shell_command.delete_old_snapshots
  data: {}
- service: hassio.backup_full
  data_template:
    name: '{{now().strftime(''%Y-%m-%d'')}}-HomeAssistant-Backup'
- service: notify.gotify
  data:
    title: Backup erstellt
    message: '{{now().strftime(''%Y-%m-%d'')}}-HomeAssistant-Backup'
mode: single
