alias: Staubsaugen
description: ''
trigger:
- platform: state
  entity_id:
  - binary_sensor.anwesend
  for:
    hours: 0
    minutes: 10
    seconds: 0
  id: Abwesenheit
  from: 'on'
  to: 'off'
- platform: time
  at: input_datetime.staubsaugen_beginn
  id: Staubsaugen beginnen
- platform: device
  device_id: e63d7afbcf7e0943762c75cef2332a73
  domain: shelly
  type: double_push
  subtype: button1
  id: Küche staubsaugen
- platform: state
  entity_id:
  - binary_sensor.staubsauger_alle_sensoren
  from: 'off'
  to: 'on'
  id: Sensoren Reinigen
- platform: time
  at: 00:00:01
  id: Sensor zurücksetzen
- platform: state
  entity_id:
  - binary_sensor.staubsauger_behaelter_entleeren
  from: 'off'
  to: 'on'
  id: Behälter entleeren
condition: []
action:
- choose:
  - conditions:
    - condition: trigger
      id: Sensor zurücksetzen
    - condition: state
      entity_id: input_boolean.staubsauger_heute_gestaubsaugt
      state: 'on'
    sequence:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.staubsauger_heute_gestaubsaugt
  - conditions:
    - condition: or
      conditions:
      - condition: trigger
        id: Abwesenheit
      - condition: trigger
        id: Staubsaugen beginnen
    - condition: state
      entity_id: binary_sensor.staubsauger_heute_reinigung_notwendig
      state: 'on'
    - condition: state
      entity_id: input_boolean.staubsauger_heute_gestaubsaugt
      state: 'off'
      enabled: true
    - condition: state
      entity_id: vacuum.roborock_s6_maxv
      state: docked
    - condition: time
      after: input_datetime.staubsaugen_beginn
      before: input_datetime.staubsaugen_ende
    sequence:
    - choose:
      - conditions:
        - condition: state
          entity_id: binary_sensor.anwesend
          state: 'off'
        sequence:
        - service: script.staubsaugen
          data:
            zustand: Abwesenheit
      - conditions:
        - condition: state
          entity_id: binary_sensor.staubsauger_zwangsreinigung
          state: 'on'
        sequence:
        - service: script.staubsaugen
          data:
            zustand: Zwangsreinigung
  - conditions:
    - condition: trigger
      id: Küche staubsaugen
    sequence:
    - service: script.staubsaugen
      data:
        zustand: Zonenreinigung
  - conditions:
    - condition: or
      conditions:
      - condition: trigger
        id: Sensoren Reinigen
      - condition: trigger
        id: Behälter entleeren
    sequence:
    - if:
      - condition: state
        entity_id: binary_sensor.anwesend
        state: 'off'
      then:
      - wait_for_trigger:
        - platform: state
          entity_id:
          - binary_sensor.anwesend
          from: 'off'
          to: 'on'
          for:
            hours: 0
            minutes: 0
            seconds: 0
        timeout:
          hours: 48
          minutes: 0
          seconds: 0
          milliseconds: 0
    - choose:
      - conditions:
        - condition: state
          entity_id: binary_sensor.staubsauger_hauptbuerste
          state: 'on'
        sequence:
        - service: notify.gotify
          data:
            message: Hauptbürste bitte reinigen!
            title: Roborock S6 MaxV
        - service: input_boolean.turn_on
          data: {}
          target:
            entity_id: input_boolean.staubsauger_hauptbuerste
      - conditions:
        - condition: state
          entity_id: binary_sensor.staubsauger_seitenbuerste
          state: 'on'
        sequence:
        - service: notify.gotify
          data:
            message: Seitenbürste bitte reinigen!
            title: Roborock S6 MaxV
        - service: input_boolean.turn_on
          data: {}
          target:
            entity_id: input_boolean.staubsauger_seitenbuerste
      - conditions:
        - condition: state
          entity_id: binary_sensor.staubsauger_filter
          state: 'on'
        sequence:
        - service: notify.gotify
          data:
            message: Filter bitte reinigen!
            title: Roborock S6 MaxV
        - service: input_boolean.turn_on
          data: {}
          target:
            entity_id: input_boolean.staubsauger_seitenbuerste
      - conditions:
        - condition: state
          entity_id: binary_sensor.staubsauger_kamerasensoren
          state: 'on'
        sequence:
        - service: notify.gotify
          data:
            message: Seitenbürste bitte reinigen!
            title: Roborock S6 MaxV
        - service: input_boolean.turn_on
          data: {}
          target:
            entity_id: input_boolean.staubsauger_seitenbuerste
      - conditions:
        - condition: trigger
          id: Behälter entleeren
        sequence:
        - service: notify.gotify
          data:
            title: Roborock S6 MaxV
            message: Staubbehälter bitte entleeren!
mode: parallel
max: 10

