id: '1672891624068'
alias: Staubsaugen
description: "15min Abwesenheit: Zwischen den eingestellten Zeiten (`input_datetime.staubsaugen_beginn`
  und `input_datetime.staubsaugen_ende`)\n wird die Wohnung gereinigt. \n\nZwangsreinigung:
  Eine Zwangsreinigung ist notwendig, wenn wenn nach eine bestimmte Anzahl an Tagen
  nicht gereinigt wurde.\n\nStaubbehälter: Nach einer Anzahl von Reinigungen (`input_number.staubsauger_entleeren`)
  wird eine Push-Benachrichtigung versendet, dass der Behälter entleert werden soll.
  \n\nSensoren: Wenn Sensoren gereinigt werden müssen, wird eine Push-Benachrichtigung
  versendet und der Counter zurückgesetzt.\n\nKüche: Wenn der Küchen-Lichtschalter
  2x schnell hintereinander gedrückt wird, wird die Küche entlang der Küchenschränke
  (Zone) gereinigt."
trigger:
- platform: state
  entity_id:
  - binary_sensor.anwesend
  from: 'on'
  to: 'off'
  id: Abwesenheit
  for:
    hours: 0
    minutes: 10
    seconds: 0
- platform: time
  at: input_datetime.staubsaugen_beginn
  id: Start
- platform: state
  entity_id:
  - binary_sensor.staubsauger_entleeren
  from: 'off'
  to: 'on'
  id: Staubbehälter
- platform: state
  entity_id:
  - sensor.staubsauger_sensoren_reinigen
  from: 'False'
  id: Sensoren
- platform: device
  device_id: e63d7afbcf7e0943762c75cef2332a73
  domain: shelly
  type: double_push
  subtype: button1
  id: Küche
condition: []
action:
- choose:
  - conditions:
    - condition: or
      conditions:
      - condition: trigger
        id: Abwesenheit
      - condition: trigger
        id: Start
    - condition: state
      entity_id: binary_sensor.anwesend
      state: 'off'
      for:
        hours: 0
        minutes: 10
        seconds: 0
    - condition: state
      entity_id: binary_sensor.staubsauger_heute_reinigung_notwendig
      state: 'on'
    - condition: time
      after: input_datetime.staubsaugen_beginn
      before: input_datetime.staubsaugen_ende
    - condition: state
      entity_id: vacuum.roborock_vacuum_a10
      state: docked
    sequence:
    - service: notify.gotify
      data:
        title: Roborock S6 MaxV
        message: Reinigung bei Abwesenheit um {{as_timestamp(now()) | timestamp_custom('%H:%M
          Uhr')}} gestartet.
    - service: vacuum.start
      data: {}
      target:
        entity_id: vacuum.roborock_vacuum_a10
    - wait_for_trigger:
      - platform: state
        entity_id:
        - vacuum.roborock_vacuum_a10
        to: returning
      continue_on_timeout: false
      timeout:
        hours: 2
        minutes: 0
        seconds: 0
        milliseconds: 0
    - service: notify.gotify
      data:
        title: Roborock S6 MaxV
        message: Reinigung um {{as_timestamp(now()) | timestamp_custom('%H:%M Uhr')}}
          abgeschlossen.
  - conditions:
    - condition: trigger
      id: Start
    - condition: state
      entity_id: binary_sensor.staubsauger_zwangsreinigung
      state: 'on'
    - condition: time
      after: input_datetime.staubsaugen_beginn
      before: input_datetime.staubsaugen_ende
    sequence:
    - service: notify.gotify
      data:
        title: Roborock S6 MaxV
        message: Reinigung nach {{ states('input_number.nach_tagen_reinigen') |
          int }} Tagen notwendig. Reinigung um {{as_timestamp(now()) | timestamp_custom('%H:%M
          Uhr') }} gestartet.
    - service: vacuum.start
      data: {}
      target:
        entity_id: vacuum.roborock_vacuum_a10
    - wait_for_trigger:
      - platform: state
        entity_id:
        - vacuum.roborock_vacuum_a10
        to: returning
      timeout:
        hours: 2
        minutes: 0
        seconds: 0
        milliseconds: 0
    - service: notify.gotify
      data:
        title: Roborock S6 MaxV
        message: Reinigung um {{as_timestamp(now()) | timestamp_custom('%H:%M Uhr')}}
          abgeschlossen.
  - conditions:
    - condition: trigger
      id: Staubbehälter
    sequence:
    - service: notify.gotify
      data:
        title: Roborock S6 MaxV
        message: Staubbehälter entleeren - {states('input_number.staubsauger_entleeren')
          | int }} wurden Reinigungen durchgeführt.
  - conditions:
    - condition: trigger
      id: Sensoren
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.staubsauger_sensoren_reinigen
        state: unavailable
    sequence:
    - service: notify.gotify
      data:
        title: Roborock S6 MaxV
        message: '{{states(''sensor.staubsauger_sensoren_reinigen'')}}
          '
    - choose:
      - conditions:
        - condition: numeric_state
          entity_id: sensor.roborock_vacuum_a10_main_brush_left
          below: 0
        sequence:
        - service: vacuum.send_command
          data:
            command: reset_consumable
            params:
            - main_brush_work_time
          target:
            entity_id: vacuum.roborock_vacuum_a10
      - conditions:
        - condition: numeric_state
          entity_id: sensor.roborock_vacuum_a10_side_brush_left
          below: 0
        sequence:
        - service: vacuum.send_command
          target:
            entity_id: vacuum.roborock_vacuum_a10
          data:
            command: reset_consumable
            params:
            - side_brush_work_time
      - conditions:
        - condition: numeric_state
          entity_id: sensor.roborock_vacuum_a10_filter_left
          below: 0
        sequence:
        - service: vacuum.send_command
          target:
            entity_id: vacuum.roborock_vacuum_a10
          data:
            command: reset_consumable
            params:
            - filter_work_time
      - conditions:
        - condition: numeric_state
          entity_id: sensor.roborock_vacuum_a10_sensor_dirty_left
          below: 0
        sequence:
        - service: vacuum.send_command
          target:
            entity_id: vacuum.roborock_vacuum_a10
          data:
            command: reset_consumable
            params:
            - sensor_dirty_time
  - conditions:
    - condition: trigger
      id: Küche
    sequence:
    - service: xiaomi_miio.vacuum_clean_zone
      data:
        zone:
        - - 20117
          - 22994
          - 21417
          - 26594
        repeats: 1
      target:
        entity_id: vacuum.roborock_vacuum_a10
mode: single
