id: '1672937116825'
alias: Szenenwechsel
description: Wenn der Sensor den Status ändert, wird dieser Wert in den Input-Helper
  `input_select.szenenauswahl` geschrieben. Dies stellt die zentrale Automation
  für die einheitliche Licht-Szenen-Steuerung für die Wohnung.
trigger:
- platform: state
  entity_id:
  - sensor.szenenauswahl
condition: []
action:
- service: input_select.select_option
  data:
    option: '{{ states(''sensor.szenenauswahl'') }}'
  target:
    entity_id: input_select.szenenauswahl
mode: single
