# ---- PING-Plattform 

## [Ping] Fernseher
## LG B9
- platform: ping
  host: !secret ip_fernseher
  name: "Fernseher"
  count: 2
  scan_interval: 3

## [Ping] NAS
## Synology Diskstation DS214play
- platform: ping
  host: !secret ip_diskstation
  name: "Diskstation"
  count: 2
  scan_interval: 15
 
# ---- Template-Plattform 
- platform: template
  sensors:

    ## [Allgemein] Anwesenheitserkennung
    ## True, wenn keiner Zuhause ist
    anwesend:
      friendly_name: "Jemand Zuhause"
      value_template: "{{is_state('person.erik','home')}}"

    ## [Staubsauger] Heute noch nicht gereinigt
    ## True, wenn heute noch nicht gereinigt wurde (auch keine kurze K체chenreinigung)
    staubsauger_heute_reinigung_notwendig:
      friendly_name: "Heute Reinigung notwendig"
      icon_template: >-
        {% if is_state('binary_sensor.staubsauger_heute_reinigung_notwendig','on') %} mdi:circle-slice-8
        {% else %} mdi:circle-outline
        {% endif %}      
      value_template: >-
        {% set letzte_reinigung = as_timestamp(states('sensor.roborock_vacuum_a10_last_clean_start')) | timestamp_custom('%d.%m.%Y') %}
        {% set automatische_reinigung =  as_timestamp(state_attr('automation.staubsaugen','last_triggered')) | timestamp_custom('%d.%m.%Y') %}
        {% set heute = as_timestamp(now()) | timestamp_custom('%d.%m.%Y') %}
        {% if letzte_reinigung != heute %} {{ true }}
        {% elif automatische_reinigung != heute %} {{ true }}
        {% else %} {{ false }}
        {% endif %}

    ## [Staubsauger] Staubbeh채lter entleeren
    ## True, wenn 'Anzahl der Gesamtreinigungen' / '(Helfer) Nach Reinigungen leeren' = Rest 0
    staubsauger_entleeren:
      friendly_name: "Beh채lter entleeren"
      icon_template: >-
        {% if is_state('binary_sensor.staubsauger_entleeren','on') %} mdi:circle-slice-8
        {% else %} mdi:circle-outline
        {% endif %}         
      value_template: >-
        {% set rest = states('sensor.roborock_vacuum_a10_total_clean_count') | int % states('input_number.staubsauger_entleeren') | int %}
        {% if rest == 0 %} {{ true }}
        {% else %} {{ false }}
        {% endif %}

    ## [Staubsauger] Zwangsreinigung
    ## True, wenn letzte Reinigung in Tagen zu lange zur체ck liegt
    staubsauger_zwangsreinigung:
      friendly_name: "Zwangsreinigung"
      icon_template: >-
        {% if is_state('binary_sensor.staubsauger_zwangsreinigung','on') %} mdi:circle-slice-8
        {% else %} mdi:circle-outline
        {% endif %} 
      value_template: >-              
        {% set letzte_reinigung = states('sensor.roborock_vacuum_a10_last_clean_start') %}
        {% set zwangsreinigung = states('input_number.nach_tagen_reinigen') | int %}
        {% set zwangsreinigung = as_datetime(letzte_reinigung) + timedelta(days=zwangsreinigung) %}
        {% if zwangsreinigung <= now() %} {{ true }}
        {% else %} {{ false }}
        {% endif %} 

    ## [Licht] Bewegung erkannt
    ## True, wenn bei einem von zwei Sensoren im Flur Bewegung erkannt wurde
    flur_bewegung_erkannt:
      friendly_name: "Flur Bewegung erkannt [ODER-FUNKTION]"
      icon_template: >-
        {% if is_state('flur_bewegung_erkannt','true') %} mdi:motion-sensor
        {% else %} mdi:motion-sensor-off
        {% endif %}
      value_template: >-
        {% set A = states('binary_sensor.flur_2_motion_2')  %}
        {% set B = states('binary_sensor.flur_motion')  %}
        {% if A == "on" or B == "on" %} {{true}}
        {% else %} {{false}}
        {% endif %}

    ## [Licht] Keine Bewegung den zwei Sensoren im Flur keine Bewegung erkannt wurde
    flur_keine_bewegung_erkannt:
      friendly_name: "Flur keine Bewegung mehr erkannt [UND-FUNKTION]"
      icon_template: >-
        {% if is_state('flur_keine_bewegung_erkannt','true') %} mdi:motion-sensor
        {% else %} mdi:motion-sensor-off
        {% endif %}
      value_template: >-
        {% set A = states('binary_sensor.flur_2_motion_2')  %}
        {% set B = states('binary_sensor.flur_motion')  %}
        {% if A == "off" and B == "off" %} {{true}}
        {% else %} {{false}}
        {% endif %}