# Kategorie: Licht
# Name: Lichtschalter
# Beschreibung: Manuell erstellter Lichtschalter für den Shelly
# Letzte Anpassung: 20.05.2023
- platform: switch
  name: Flur
  entity_id: switch.shellyplus1_441793a3e76c_switch_0