# Kategorie: Licht
# Name: TV Beleuchtung
# Beschreibung: Fasse die drei Lampen zu einer Gruppe zusammen
# Letzte Anpassung: 20.05.2023
- platform: group
  name: TV Licht
  entities:
    - light.lampe_links
    - light.lampe_mitte
    - light.lampe_rechts